config/routes.rb
Rails.application.routes.draw do

  get 'todos', to: 'todos#index'

  get 'todos/new'

  post 'todos', to: 'todos#create'

  get 'todos/:id', to: 'todos#show', as: 'todo'

  get 'complete/:id', to: 'todos#complete', as: 'complete'

  get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'

  patch 'todos/:id', to: 'todos#update'

  delete 'todos/:id', to: 'todos#destroy'

  get 'todos_list', to: 'todos#list'

  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todos = Todo.new
  end

  def create
    @todos = Todo.new(todo_params)
    @todos.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'todos/navbar' %>
  <div class="container main mb-5">
    <%= yield %>
  </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/todos/_form.html.erb
<h1 class="color-form">Ingrese texto para crear un todo</h1>
<%= form_with model: Todo.new, local: true do |t| %>
  <%= t.text_field :description %>
  <%= t.submit "Enviar", class: 'color-enviar' %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active p-3">
        <%= link_to 'Index de todo', todos_path, class: 'color-letra' %>
      </li>
      <li class="nav-item p-3">
        <%= link_to 'Listar todo', todos_list_path, class: 'color-letra' %>
      </li>
      <li class="nav-item p-3">
        <%= link_to 'crear un todo', todos_new_path, class: 'color-letra' %>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<div class="card mb-3 ml-3 mt-3 style="width: 40rem;"">
  <div class="card-body">
    <%= form_with model: @todo, local: true do |t| %>
      <%= t.text_field :description %>
      <%= t.submit "Enviar", class: 'color-enviar' %>
    <% end %>
  </div>
</div>

app/views/todos/index.html.erb
<div class="card mb-3 ml-3 mt-3">
  <div class="card-body">
    <% @todos.each do |todo| %>
      <h1> <%= link_to todo.description, todo, class: 'color-todo' %> </h1>
      <% if todo.completed == true %>
        Tarea completada
      <% else %>
        Tarea no completada
        <button type="button" class="btn ml-3">
        <%= link_to 'Completar', complete_path(todo), class: 'color-letra' %>
        </button>
      <% end %>
      <button type="button" class="btn ml-3">
      <%= link_to 'Editar', todo_edit_path(todo), class: 'color-letra' %>
      </button>
      <button type="button" class="btn ml-3">
      <%= link_to 'Eliminar', todo, method: :delete, class: 'color-letra' %>
      </button>
    <% end %>

  </div>
</div>
<button type="button" class="btn ml-3"> <%= link_to 'Crear ToDo', todos_new_path, class: 'color-letra' %> </button>

app/views/todos/list.html.erb
  <div class="row">
    <div class="col-md-6">
      <div class="card mb-3 ml-3 mt-3">
        <div class="card-body">
          <h1 class="titulo p-3">No completados</h1>
          <% @todos.each do |todo| %>
            <% if todo.completed != true %>
              <h3 class="pl-3"> <%= link_to todo.description, todo, class: 'color-todo' %> </h3> <br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-3 ml-3 mt-3">
        <div class="card-body">
          <h1 class="titulo p-3">Completados</h1>
          <% @todos.each do |todo| %>
            <% if todo.completed == true %>
              <h3 class="pl-3"> <%= link_to todo.description, todo, class: 'color-todo' %> </h3> <br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/todos/new.html.erb
<div class="card mb-3 ml-3 mt-3" style="max-width: 40rem;">
  <div class="card-body">
    <%= render 'todos/form' %>
</div>

app/views/todos/show.html.erb
<div class="card mb-3 ml-3 mt-3 style="width: 40rem;"">
  <div class="card-body">
<h1 class="color-form"> <%= @todo.description %> </h1>
<% if @todo.completed == true %>
  Completada
<% end %>
</div>
</div>